### ISSUE TITLE
Missing path component in client_id when creating IndieAuth request

### ISSUE THREAD

**Issue by jlelse** [alltogethernow/server#24]
According to [the IndieAuth spec](https://indieauth.spec.indieweb.org/#client-identifier-p-1), the client_id "MUST contain a path component", but it doesn't. It's just "https://alltogethernow.io" instead of "https://alltogethernow.io/". This makes me (and @kandr3s) fail to login.

**Comment by grantcodes** [comment]
Thanks for the report, I've just added that path to the client id.

Let me know if you see any issues with it.

**Comment by jlelse** [comment]
Thanks a lot!
