### ISSUE TITLE
Error loading channels

### ISSUE THREAD

**Issue by grantcodes** [alltogethernow/server#4]
From https://github.com/cleverdevil/together/issues/95

After logging in I can no longer see any channels I have set up in Aperture. Sidebar just has the message "error loading channels".

Tried this in both Firefox and Chrome on a Mac - Same issue. Looking at the network responses for https://alltogethernow.io/ I can see a 400 for Variable "$channel" of required type "String!" was not provided.

`{"errors":[{"message":"Variable \"$channel\" of required type \"String!\" was not provided.","locations":[{"line":1,"column":21}],"extensions":{"code":"INTERNAL_SERVER_ERROR"}}]}`

I tried revoking the token in my Known site but it still has this error. Using Indigenous on Android and Monocle on web and both work fine.

Param information after clearing browser cache and logging back in.

`{"operationName":"TimelineQuery","variables":{},"extensions":{},"query":"query TimelineQuery($channel: String!, $after: String, $before: String, $limit: Int) {\n timeline(channel: $channel, after: $after, before: $before, limit: $limit) {\n channel\n after\n before\n items {\n ...PostFragment\n refs {\n ...PostFragment\n __typename\n }\n __typename\n }\n __typename\n }\n}\n\nfragment PostFragment on Post {\n ...PostProperties\n refs {\n ...PostProperties\n refs {\n ...PostProperties\n __typename\n }\n __typename\n }\n __typename\n}\n\nfragment PostProperties on Post {\n _id\n _is_read\n type\n url\n published\n postType\n name\n category\n postStatus\n visibility\n likeOf\n repostOf\n quotationOf\n bookmarkOf\n photo\n video\n audio\n checkin {\n type\n name\n latitude\n longitude\n url\n __typename\n }\n location {\n type\n name\n latitude\n longitude\n url\n __typename\n }\n content {\n text\n html\n __typename\n }\n author {\n ...AuthorFragment\n __typename\n }\n __typename\n}\n\nfragment AuthorFragment on PostAuthor {\n name\n url\n photo\n __typename\n}\n"}`

**Comment by grantcodes** [comment]
Hey @davidmead I moved the issue here since I moved the repos.

I updated Together to v3.6.1 now which will stop that `TimelineQuery` error you were getting, but that is actually different from the error loading channels.

If you still have an error and open up the console there will be a link to open an issue with a bunch of information prefilled.

**Comment by davidmead** [comment]
OK @grantcodes. I tried version 3.6.2 and I'm still getting the same error.  I even tried after disabling Adblocker & Privacy Badger on the site (just in case).  I'll use the link(s) in the console to file.
