### ISSUE TITLE
GraphQL Error: Invalid URL: 

### ISSUE THREAD

**Issue by davidmead** [alltogethernow/server#5]
**Describe the bug**
I encountered a GraphQL error: `Invalid URL: ` on the url undefined

**Expected Behavior**
{{A clear and concise description of what you expected to happen.}}
The channels I'm subscribed to would show on the left-hand side of the screen

**More Info**
{{Add any other context about the problem here.}}

**Error Message**
```javascript
{
  "message": "Invalid URL: ",
  "locations": [
    {
      "line": 2,
      "column": 3
    }
  ],
  "path": [
    "channels"
  ],
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR",
    "exception": {
      "input": ""
    }
  }
}
```

**Operation Info**
```javascript
{
  "operationName": "GetChannels",
  "variables": {},
  "query": {
    "kind": "Document",
    "loc": {
      "start": 0,
      "end": 214
    }
  }
}
```

**Comment by grantcodes** [comment]
Ok! So I figured out why it wasn't working for you but I am not sure what caused it...

The backend didn't have your microsub endpoint stored for some reason. I have manually added it now, so hopefully together will finally work for you now.

Just for future bug fixing purposes, do you know if maybe you tried to login before your microsub endpoint was set up on your website? I could see that being a potential issue.

**Comment by davidmead** [comment]
I had to renew my SSL so I've only just looked at this. I don't think I logged in before it was set up, but maybe when I updated Known there was a gap then?

I just tired logging back in and it's the same. 'Error loading channels'.

I'll try revoking all the alltogether.io tokens in Known, log out, and try again.

**Comment by davidmead** [comment]
no luck. same problem

**Comment by grantcodes** [comment]
Hey @davidmead I made another update that fixed something that looked very similar to your issue for micro.blog that was to do with trailing slashes. So maybe that might have been the same as your issue 🤞

**Comment by davidmead** [comment]
No luck.

I did the following:

- revoked the tokens in Known
- cleared Firefox's cache, history, and offline data
- fully closed Firefox and opened again

Logged in to version 3.6.4 and the same problem.  I also still cannot see any settings.

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/1266930/61788639-91afae00-ade0-11e9-89df-53f8aef3fed8.png">

**Comment by grantcodes** [comment]
Ok, this time I really think I have fixed it!

I wasn't refreshing access tokens in the database 🤦‍♂️ if you log out and back in again it should refresh your token and finally work

**Comment by davidmead** [comment]
Looks like that did it @grantcodes :-)

<img width="668" alt="image" src="https://user-images.githubusercontent.com/1266930/61995996-5a9a0080-b05d-11e9-9ad6-5dd145186ac4.png">

Thanks.

**Comment by grantcodes** [comment]
🎉🎉 finally!

Thanks for all your patience
