### ISSUE TITLE
GraphQL Error: 404: Not Found

### ISSUE THREAD

**Issue by frankmeeuwsen** [alltogethernow/server#6]
**Describe the bug**
I encountered a GraphQL error: `404: Not Found` when I logged in with my URL https://diggingthedigital.com/

**Expected Behavior**
I expected Together to load my Aperture subscriptions and show them. In the header of my site the microsub element only links to the Aperture URL.

**Error Message**
```javascript
{
  "message": "404: Not Found",
  "locations": [
    {
      "line": 2,
      "column": 3
    }
  ],
  "path": [
    "timeline"
  ],
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR",
    "response": {
      "url": "https://diggingthedigital.com/wp-json/yarns-microsub/1.0/endpoint?action=timeline&channel=notifications&limit=20",
      "status": 404,
      "statusText": "Not Found",
      "body": {
        "code": "rest_no_route",
        "message": "Geen route gevonden die overeenkomt met de URL en aanvraagmethode",
        "data": {
          "status": 404
        }
      }
    }
  }
}
```

**Operation Info**
```javascript
{
  "operationName": "GetChannels",
  "variables": {},
  "query": {
    "kind": "Document",
    "loc": {
      "start": 0,
      "end": 214
    }
  }
}
```

**Comment by grantcodes** [comment]
Ah so the microsub endpoint wasn't actually being updated because of a dumb typo!

Updated now, so with one more logout and in it really should update this time

**Comment by frankmeeuwsen** [comment]
Yes it does! Thanks for the fix!





Op wo jul 24 2019, om 23:35 schreef Grant Richmond:
